<?php

return [
    'adminEmail' => 'admin@example.com',
	'defaultImageFile' => 'label_image_00000.jpg',
	'defaultImageWidth' => 300,
	'wotdMinRating' => 89,
	'perm_list' => ['NONE', 'USER', 'ADMIN'],
	'varietal_types' => [
		'Blush'=>'Blush',
		'Red'=>'Red',
		'White'=>'White',
		'Sparkling'=>'Sparkling',
		'Desert'=>'Desert',
	],
	'bottle_sizes' => [
		'750ml'=>'750ml',
		'375ml'=>'375ml',
		'500ml'=>'500ml',
		'Pony'=>'Pony',
		'Magnum'=>'Magnum',
		'Marie-Jean'=>'Marie-Jean',
		'Double Mag'=>'Double Mag',
		'Jeroboam'=>'Jeroboam',
		'Reboboam'=>'Reboboam',
		'Imperial'=>'Imperial',
		'Methuselah'=>'Methuselah',
		'Salmanazar'=>'Salmanazar',
		'Balthazar'=>'Balthazar',
		'Nebuchadnezzar'=>'Nebuchadnezzar',
		'Soverign'=>'Soverign',
	],
	'apiUrl' => 'http://api.upcdatabase.org',
	'apiKey' => '7fe0dbfc703f4a0803a0cd7ca386b50f',
	'upcDBErrorCodes' => [
		'101' => 'API Key length is incorrect',
		'105' => 'API Key incorrect',
		'199' => 'No more API requests remaining',
		'201' => 'You did not enter a code',
		'205' => 'The code you entered was non-numeric',
		'301' => 'Code does not exist',
		'500' => 'High server load',
	],
];
